# -----------------------------------------------------
# Master Configuration File
# -----------------------------------------------------

app:
  title: Tweasier
  tagline: A new Twitter application which has been designed to make life on Twitter even easier.
  version: 0.0.1
  twitter_handle: tweasier
  twitter_url: http://twitter.com/tweasier

email:
  info: info@tweasier.com
  support: support@tweasier.com

twitter:
  auth_token: Tw4Gah4iMV5Vqjqy4uzIw
  auth_secret: ZWTIjo46gJxnMmvsKw0bJRm6wcWkbKyOvmykYHDSXh8
  request_limit: 150
  settings_url: http://twitter.com/account/settings

blog:
  url: http://tweasier.com/blog
  feed_url: http://feeds.feedburner.com/tweasier
  cache_period: 2 # hours

production:
  username: chrisnorton
  password: justforme

charts:
  background_colour: efefef

options:
  email_notifications:
    - none
    - daily
    - weekly

bitly:
  home_url: http://bit.ly
  signup_url: http://bit.ly/account/register

google_maps:
  api_key: ABQIAAAA-eURyKhSLzwC3AewI3OdFhQLNg9bWT2-pdEz34bH9gru3A-k4xRYiXkAN38OSuEZBwbag76oQqkE8A

unfollower:
  time_period: 3 # days

# Commenting the maintenance message back in will show it
# in the master layout. Use this for announcements etc.
# maintenance:
#   message: We are currently updating the site to bring you better stability and performance. Sorry for any inconvenience this may cause.
