# ---------------------------------------------------------------------
# DB Configuration
# ---------------------------------------------------------------------

mysql: &mysql
  adapter: mysql
  host: localhost
  username: twdeploy
  password: Gazu=wAbect19
  
development:
  database: tweasier_legacy_development
  adapter: mysql
  host: localhost
  username: root
  password: root

production_private:
  database: tweasier_private_production
  <<: *mysql
